### ISSUE TITLE
Cuk4Nuke fails on creating object

### ISSUE THREAD

**Issue by thenapoleon** [richardlawrence/Cuke4Nuke#35]
Hi,

after installing cuk4nuke following instructions, I am getting this error when trying to run a test:

```
Given a logged on agent
  ComponentActivator: could not instantiate Fortis.Edison.WebSite.Features.Features.step_definitions.Steps (Castle.MicroKernel.ComponentActivator.ComponentActivatorException from :3901)
     at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.CreateInstance(CreationContext context, Object[] arguments, Type[] signature)
     at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.Instantiate(CreationContext context)
     at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.InternalCreate(CreationContext context)
     at Castle.MicroKernel.ComponentActivator.AbstractComponentActivator.Create(CreationContext context)
     at Castle.MicroKernel.Lifestyle.SingletonLifestyleManager.Resolve(CreationContext context)
     at Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context)
     at Castle.MicroKernel.DefaultKernel.ResolveComponent(IHandler handler,Type service, IDictionary additionalArguments)
     at Cuke4Nuke.Core.ObjectFactory.GetObject(Type type)
     at Cuke4Nuke.Core.StepDefinition.Invoke(ObjectFactory objectFactory, String[] args)
     at Cuke4Nuke.Core.Processor.Invoke(String id, String[] args)
     at Cuke4Nuke.Core.Processor.Process(String request)
  features\agent_can_add_customer.feature:8:in `Given a logged on agent'
```

What am I missing?

Thanks

**Comment by richardlawrence** [comment]
Can you please share your step definition class?

**Comment by thenapoleon** [comment]
I have found what my problem was, I think this was due to me not having added the cucumber.wire file. I downloaded the source and was able to run the google sample, so I guessed I was doing something wrong and managed to fix this problem.
